windows:
  hosts:
    AE50MSSQL:
      ansible_host: 10.10.240.150
    AE50SERVER:
      ansible_host: 10.10.240.151
    AE50CLIENT:
      ansible_host: 10.10.240.152
linux:
  hosts:
    AETESTSQL01:
      ansible_host: 10.10.240.17
    AEDEMOSQL01:
      ansible_host: 10.10.240.18
    AEMONITOR01:
      ansible_host: 10.10.240.11
mssql-linux:
  hosts:
    AETESTSQL01:
      ansible_host: 10.10.240.17
    AEDEMOSQL01:
      ansible_host: 10.10.240.18
