---
- name: install IIS
  hosts: test
  gather_facts: true
  vars:
    ansible_user: "Administrator"
    ansible_port: 22
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
    ansible_ssh_retries: 3
    ansible_shell_type: powershell
    ansible_become_method: runas
    ansible_become_user: "{{ ansible_user }}"
  tasks:
    - ansible.windows.win_feature:
        name: "Web-Server"
        state: present
        restart: yes
        include_sub_features: yes
        include_management_tools: yes
