---
# Tasks to patch a Linux Server using apt
- name: Linux update playbook
  hosts: linux
  strategy: free
  become: true
  vars:
    ansible_user: "ansible"

  tasks:
    - name: Update all packages to their latest version
      ansible.builtin.apt:
        update_cache: true
        autoremove: true
        upgrade: safe
        name: "*"

    - name: Check if a reboot is required.
      ansible.builtin.stat:
        path: /var/run/reboot-required
        get_checksum: false
      register: reboot_required_file

    - name: Reboot the server (if required).
      ansible.builtin.reboot:
      when: reboot_required_file.stat.exists

    - name: Remove unneeded dependencies
      ansible.builtin.apt:
        autoremove: true
