---
# Tasks to patch a Linux Server using apt
- name: Linux update playbook
  hosts: linux
  strategy: free
  become: true
  vars:
    ansible_user: "ansible"

  tasks:
    - name: update all packages to their latest version
      ansible.builtin.apt:
        name: "*"
        state: latest
        upgrade: dist
        update_cache: yes
