---
# Tasks to patch a Linux Server using apt
- name: Linux update playbook
  # gather_facts: no
  hosts: linux
  strategy: free
  vars:
    ansible_user: "ansible"
  become: true

  tasks:
    - name: update all packages to their latest version
      become: true
      ansible.builtin.apt:
        name: "*"
        state: latest
        update_cache: yes
