services:
  gatus:
    container_name: gatus
    image: twinproduction/gatus
    restart: unless-stopped
    volumes:
      - ./gatus:/config
    networks:
      - monitoring
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    depends_on:
      - gatus
    healthcheck:
      test: ["CMD-SHELL", "wget http://localhost:9090/ > /dev/null ||exit 1"]
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.retention.time=30d"
      - "--web.enable-otlp-receiver"
    networks:
      - monitoring
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    depends_on:
      - prometheus
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --silent --fail http://localhost:3000/ > /dev/null || exit 1",
        ]
    environment:
      - GF_SERVER_ROOT_URL=https://10.10.240.11
      - GF_PLUGINS_PREINSTALL=grafana-clock-panel
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - monitoring
  nginx:
    container_name: nginx
    restart: always
    image: nginx:latest
    depends_on:
      - grafana
      - gatus
      - prometheus
    ports:
      - "80:80"
      - "443:443"
      - "9090:9090"
      - "8080:8080"
    volumes:
      - ./nginx/:/etc/nginx
    networks:
      - monitoring
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --silent --fail http://grafana:3000/ > /dev/null || exit 1",
        ]
volumes:
  prometheus-data:
    external: true
  grafana-data:
    external: true
networks:
  monitoring:
    driver: bridge
