receivers:
  # Default OTLP receiver on localhost only
  otlp:
    protocols:
      grpc:
        endpoint: 127.0.0.1:4317
      http:
        endpoint: 127.0.0.1:4318
  # Scrape host metrics automatically every minute
  host_metrics:
    scrapers:
      cpu:
      disk:
      filesystem:
      load:
      memory:
      network:
      process:
      processes:
      paging:
      system:
  # Events from Event Log
  windows_event_log:
    channel: application
    # Uncomment to scrape logs from a directory and enter receiver-name into logs pipeline.
    # Automatically attaches to the end of each discovered log file.
    # Multiple formats can be used.
    # For further information please see: https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/filelogreceiver
    # file_log:
    #   include:
    #     - /path/to/logfiles/*.log
# Further processing for collected data
processors:
  memory_limiter:
    check_interval: 10s
    limit_mib: 1000
    spike_limit_mib: 500
  batch:
    timeout: 60s
exporters:
  otlp_grpc:
    endpoint: 10.10.240.11:4317
    tls:
      ca_file: /path/to/ca.pem
      cert_file: /path/to/client-cert.pem
      key_file: /path/to/client-key.pem
      insecure: false
      # Use Self Signed Certificates
      insecure_skip_verify: true
    # Persist Data on Disk in case the exporter fails e.g. because of no network
    sending_queue:
      storage: file_storage
extensions:
  file_storage:
    directory: ./queue
    create_directory: true
service:
  extensions: [file_storage]
  pipelines:
    traces:
      receivers: [otlp]
      processors: []
      exporters: [otlp_grpc]
    metrics:
      receivers: [otlp, host_metrics]
      processors: []
      exporters: [otlp_grpc]
    logs:
      receivers: [otlp, windows_event_log]
      processors: []
      exporters: [otlp_grpc]
